name: build-desktop-apps
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyInstaller
        run: python -m pip install --upgrade pip pyinstaller

      # Make ffmpeg executable on Unix platforms
      - name: Mark FFmpeg executable (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x tools/ffmpeg/linux/ffmpeg || true
          chmod +x tools/ffmpeg/macos/ffmpeg || true

      # Compute add-binary argument and pick the right FFmpeg path per OS
      - name: Compute build vars
        id: cfg
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "SEP=;" >> $GITHUB_OUTPUT
            echo "FF=tools/ffmpeg/windows/ffmpeg.exe" >> $GITHUB_OUTPUT
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "SEP=:" >> $GITHUB_OUTPUT
            echo "FF=tools/ffmpeg/macos/ffmpeg" >> $GITHUB_OUTPUT
          else
            echo "SEP=:" >> $GITHUB_OUTPUT
            echo "FF=tools/ffmpeg/linux/ffmpeg" >> $GITHUB_OUTPUT
          fi

      - name: Build receiver (PyInstaller)
        run: |
          pyinstaller --onefile --windowed \
            --add-binary "${{ steps.cfg.outputs.FF }}${{ steps.cfg.outputs.SEP }}ffmpeg" \
            receiver_gui.py

      - name: Build sender (PyInstaller)
        run: |
          pyinstaller --onefile --windowed \
            --add-binary "${{ steps.cfg.outputs.FF }}${{ steps.cfg.outputs.SEP }}ffmpeg" \
            sender_gui.py

      - name: List dist
        run: ls -la dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ runner.os }}
          path: |
            dist/receiver_gui*
            dist/sender_gui*
